/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.ProductsInvoListener;
import model.InvoCustomer;
import model.CustomerInvoGridModel;
import model.InvoRecordsGridModel;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class InvoFrame extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceFrame
     */
    public InvoFrame() {
        initComponents();
        list.defultinvoicesGrid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invoTable = new javax.swing.JTable();
        invoTable.getSelectionModel().addListSelectionListener(list);
        createInvoBTN = new javax.swing.JButton();
        createInvoBTN.addActionListener(list);
        deleteInvoBTN = new javax.swing.JButton();
        deleteInvoBTN.addActionListener(list);
        jLabel_01 = new javax.swing.JLabel();
        jLabel_02 = new javax.swing.JLabel();
        jLabel_03 = new javax.swing.JLabel();
        jLabel04 = new javax.swing.JLabel();
        clientNameTF = new javax.swing.JTextField();
        invoDateTF = new javax.swing.JTextField();
        invNumLbl = new javax.swing.JLabel();
        invTotalLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        invLnsTable = new javax.swing.JTable();
        createLnBtn = new javax.swing.JButton();
        createLnBtn.addActionListener(list);
        deleteLnBtn = new javax.swing.JButton();
        deleteLnBtn.addActionListener(list);
        jMenuBar01 = new javax.swing.JMenuBar();
        jMenu01 = new javax.swing.JMenu();
        loadMenuItems = new javax.swing.JMenuItem();
        loadMenuItems.addActionListener(list);
        saveMenuItems = new javax.swing.JMenuItem();
        saveMenuItems.addActionListener(list);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(invoTable);

        createInvoBTN.setText("Create New Invoice");
        createInvoBTN.setActionCommand("CreateNewInvoice");

        deleteInvoBTN.setText("Delete Invoice");
        deleteInvoBTN.setActionCommand("DeleteInvoice");

        jLabel_01.setText("Invoice Number");

        jLabel_02.setText("Invoice Date");

        jLabel_03.setText("Customer name");

        jLabel04.setText("Invoice Total");

        invLnsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(invLnsTable);

        createLnBtn.setText("Create New Item");
        createLnBtn.setActionCommand("CreateNewLine");

        deleteLnBtn.setText("Delete Item");
        deleteLnBtn.setActionCommand("DeleteLine");

        jMenu01.setText("File");

        loadMenuItems.setText("Load File");
        loadMenuItems.setActionCommand("LoadFile");
        jMenu01.add(loadMenuItems);

        saveMenuItems.setText("Save File");
        saveMenuItems.setActionCommand("SaveFile");
        jMenu01.add(saveMenuItems);

        jMenuBar01.add(jMenu01);

        setJMenuBar(jMenuBar01);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_03)
                                            .addComponent(jLabel_01)
                                            .addComponent(jLabel_02)
                                            .addComponent(jLabel04))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clientNameTF)
                                            .addComponent(invoDateTF)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(invNumLbl)
                                                    .addComponent(invTotalLbl))
                                                .addGap(0, 352, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(createLnBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteLnBtn)
                                .addGap(113, 113, 113))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(createInvoBTN)
                        .addGap(87, 87, 87)
                        .addComponent(deleteInvoBTN)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_01)
                            .addComponent(invNumLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_02)
                            .addComponent(invoDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_03)
                            .addComponent(clientNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel04)
                            .addComponent(invTotalLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createLnBtn)
                            .addComponent(deleteLnBtn))
                        .addGap(44, 44, 44)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteInvoBTN)
                    .addComponent(createInvoBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clientNameTF;
    private javax.swing.JButton createInvoBTN;
    private javax.swing.JButton createLnBtn;
    private javax.swing.JButton deleteInvoBTN;
    private javax.swing.JButton deleteLnBtn;
    private javax.swing.JTable invLnsTable;
    private javax.swing.JLabel invNumLbl;
    private javax.swing.JLabel invTotalLbl;
    private javax.swing.JTextField invoDateTF;
    private javax.swing.JTable invoTable;
    private javax.swing.JLabel jLabel04;
    private javax.swing.JLabel jLabel_01;
    private javax.swing.JLabel jLabel_02;
    private javax.swing.JLabel jLabel_03;
    private javax.swing.JMenu jMenu01;
    private javax.swing.JMenuBar jMenuBar01;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadMenuItems;
    private javax.swing.JMenuItem saveMenuItems;
    // End of variables declaration//GEN-END:variables

    private List<InvoCustomer> invoList = new ArrayList<>();
    private CustomerInvoGridModel customerInvoTable;
    private InvoRecordsGridModel invoRecordsGridModel;
    private InvoCustomerDialog clientDialog;
    private InvoRecordDialog invoRecordDialog;
    private ProductsInvoListener list = new ProductsInvoListener(this);

    public ProductsInvoListener getListener() {
        return list;
    }

    public void setClientInvoDialog(InvoCustomerDialog CustomerDialog) {
        this.clientDialog = CustomerDialog;
    }

    public void setInvoDialog(InvoRecordDialog InvoiceDialog) {
        this.invoRecordDialog= InvoiceDialog;
    }

    public void setClientInvoTable(CustomerInvoGridModel invoiceCustomerGridModel) {
        this.customerInvoTable = invoiceCustomerGridModel;
    }

    public void setInvoRecordsGridModel(InvoRecordsGridModel invoiceRecordsGridModel) {
        this.invoRecordsGridModel = invoiceRecordsGridModel;
    }

    public JButton getCreateInvoBtn() {
        return createInvoBTN;
    }

    public JButton createInvoRecordBtn() {
        return createLnBtn;
    }

    public JTextField getClientNameTF() {
        return clientNameTF;
    }

    public JButton getDeleteInvoBtn() {
        return deleteInvoBTN;
    }

    public JButton getDeleteLnBtn() {
        return deleteLnBtn;
    }

    public JTextField getInvoDateTF() {
        return invoDateTF;
    }

    public JTable getInvoLnsTable() {
        return invLnsTable;
    }

    public JLabel getInvoNumLbl() {
        return invNumLbl;
    }

    public JLabel getInvoTotalLbl() {
        return invTotalLbl;
    }

    public JTable getInvoGrid() {
        return invoTable;
    }

    public JMenuItem getLoadingMenuItems() {
        return loadMenuItems;
    }

    public JMenuItem getSavingMenuItem() {
        return saveMenuItems;
    }

    public List<InvoCustomer> getInvoListing() {
        return invoList;
    }

    public CustomerInvoGridModel getClientInvoGridModel() {
        return customerInvoTable;
    }

    public InvoRecordsGridModel getInvoLnsTableModel() {
        return invoRecordsGridModel;
    }

    public InvoCustomerDialog getCustomerDialog() {
        return clientDialog;
    }

    public InvoRecordDialog getInvoDialog() {
        return invoRecordDialog;
    }


}
